### ISSUE TITLE
Calculo de promedio gastos e ingresos

### ISSUE THREAD

**Issue by G33N** [G33N/wiki2#5]
Estaba mal la referencia a el atributo importe de cada gasto esta es la funcion original:

`$totalIngresos=0;
		$cantidadGastos=count($this->ingresos[$mes]);
		for($i = 0 ; $i < count($this->ingresos[$mes]); $i++){
			$totalIngresos = $totalIngresos + $this->ingresos[$mes]["importe"];
		}`

Solución fue hacer referencia a `$this->ingresos[$mes][$i]["importe]`

**Comment by n0rb3r7** [comment]
Después de cambiar y agregar el índice $i o $n como abajo, se quita el count dentro del for, porque ya se tiene la cantidad de ingresos con la variable $cantidadIngresos.
`	public function promedioIngresos($mes){
		$totalIngresos=0;
		$cantidadIngresos=count($this->ingresos[$mes]);
		for($n = 0 ; $n < $cantidadIngresos ; $n++){
			$totalIngresos = $totalIngresos + $this->ingresos[$mes][$n]["importe"];
		}
		$promedioIngresos = $totalIngresos/$cantidadIngresos;
		return $promedioIngresos;

	}`

**Comment by n0rb3r7** [comment]
Después de cambiar y agregar el índice $i o $n como abajo, se quita el count dentro del for, porque ya se tiene la cantidad de ingresos con la variable $cantidadIngresos.
```
public function promedioIngresos($mes){
$totalIngresos=0;
$cantidadIngresos=count($this->ingresos[$mes]);
for($n = 0 ; $n < $cantidadIngresos ; $n++){
$totalIngresos = $totalIngresos + $this->ingresos[$mes][$n]["importe"];
}
$promedioIngresos = $totalIngresos/$cantidadIngresos;
return $promedioIngresos;

}
```
